# Class: profiles::nagios::configure
#  
#   This class set up necessary config files for Nagios
#
class profiles::nagios::configure {
  $nagios_config_path    = $profiles::nagios::config_path
  $nagios_admin_user     = $profiles::nagios::admin_user
  $nagios_admin_password = Sensitive($profiles::nagios::admin_password)
  $owner                 = $profiles::nagios::owner
  $group                 = $profiles::nagios::group

  File {
    owner => $owner,
    group => $group,
  }

  exec { "Create ${nagios_admin_user} for Nginx Authentication":
    command => "htpasswd -nbm ${nagios_admin_user} ${nagios_admin_password.unwrap()} > ${nagios_config_path}/htpasswd.users",
    path    => ['/usr/bin','/usr/sbin'],
    creates => "${nagios_config_path}/htpasswd.users",
  }

  # Fix Nginx can't find path of /cgi-bin/*.cgi in the "root" path at /usr/local/nagios/share 
  file { '/usr/local/nagios/share/cgi-bin':
    ensure => link,
    target => '/usr/local/nagios/sbin',
  }

  # Create folder to store config files that we create manually or by Puppet.
  file { "${nagios_config_path}/objects/servers":
    ensure => directory,
  }

  # Create folder to store all config files generated by consul-template
  file { "${nagios_config_path}/objects/consul_sd_configs":
    ensure => directory,
  }

  # Path to store host config files when we add them manually
  file_line { 'Add servers object path':
    ensure => present,
    path   => "${nagios_config_path}/nagios.cfg",
    line   => "cfg_dir=${nagios_config_path}/objects/servers",
    after  => "#cfg_dir=${nagios_config_path}/servers",
  }

  # Path to store host config files generated by Consul
  file_line { 'Add consul-generated object path':
    ensure => present,
    path   => "${nagios_config_path}/nagios.cfg",
    line   => "cfg_dir=${nagios_config_path}/objects/consul_sd_configs",
    after  => "#cfg_dir=${nagios_config_path}/servers",
  }

  # If you have any other username, you will need to add that user in all fields "authorized_*"" below. 
  file_line { 'Set value for authorized_for_system_information ':
    ensure => present,
    path   => "${nagios_config_path}/cgi.cfg",
    line   => "authorized_for_system_information=${nagios_admin_user}",
    match  => '^authorized_for_system_information=',
  }

  file_line { 'Set value for authorized_for_configuration_information ':
    ensure => present,
    path   => "${nagios_config_path}/cgi.cfg",
    line   => "authorized_for_configuration_information=${nagios_admin_user}",
    match  => '^authorized_for_configuration_information=',
  }

  file_line { 'Set value for authorized_for_system_commands ':
    ensure => present,
    path   => "${nagios_config_path}/cgi.cfg",
    line   => "authorized_for_system_commands=${nagios_admin_user}",
    match  => '^authorized_for_system_commands=',
  }

  file_line { 'Set value for authorized_for_all_services ':
    ensure => present,
    path   => "${nagios_config_path}/cgi.cfg",
    line   => "authorized_for_all_services=${nagios_admin_user}",
    match  => '^authorized_for_all_services=',
  }

  file_line { 'Set value for authorized_for_all_hosts ':
    ensure => present,
    path   => "${nagios_config_path}/cgi.cfg",
    line   => "authorized_for_all_hosts=${nagios_admin_user}",
    match  => '^authorized_for_all_hosts=',
  }

  file_line { 'Set value for authorized_for_all_service_commands ':
    ensure => present,
    path   => "${nagios_config_path}/cgi.cfg",
    line   => "authorized_for_all_service_commands=${nagios_admin_user}",
    match  => '^authorized_for_all_service_commands=',
  }

  file_line { 'Set value for authorized_for_all_host_commands ':
    ensure => present,
    path   => "${nagios_config_path}/cgi.cfg",
    line   => "authorized_for_all_host_commands=${nagios_admin_user}",
    match  => '^authorized_for_all_host_commands=',
  }

  # Set up Host Template Definition file
  file { "${nagios_config_path}/objects/servers/hosts-template.cfg":
    ensure  => file,
    source  => 'puppet:///modules/profiles/nagios/etc/hosts-template.cfg',
    require => File["${nagios_config_path}/objects/servers"],
  }

  # Set up Service Template Definition file
  file { "${nagios_config_path}/objects/servers/services-template.cfg":
    ensure  => file,
    source  => 'puppet:///modules/profiles/nagios/etc/services-template.cfg',
    require => File["${nagios_config_path}/objects/servers"],
  }

  # Set up Contact and Contact Group Definition file
  file { "${nagios_config_path}/objects/servers/contact-template.cfg":
    ensure  => file,
    source  => 'puppet:///modules/profiles/nagios/etc/contact-template.cfg',
    require => File["${nagios_config_path}/objects/servers"],
    notify  => Exec['Testing Nagios Config'],
  }

  # Set up Nagios Command Template Definition file
  Nagios_command {
    ensure  => present,
    mode    => '0644',
    target  => "${nagios_config_path}/objects/servers/nagios_commands.cfg",
    notify  => Service['nagios'],
    require => File["${nagios_config_path}/objects/servers"],
  }

  create_resources(nagios_command, lookup('profiles::nagios::commands', Hash, 'deep'))

  # Append more service types if you want to add
  $services = ['nagios-common-services']
  profiles::nagios::consul_template { 'nagios-hosts': }
  profiles::nagios::consul_template { $services: }
}
