# Class: profiles::nagios::consul_template
#
# This module manages the nagios consul templates
#
define profiles::nagios::consul_template (
  String        $perms = '0644',
  Array[String] $command = ["systemctl", "reload", "nagios"],
  String        $owner = 'consul',
  String        $group = 'consul',
) {
  $template = "/opt/consul-template/${name}.cfg.ctmpl"
  $target   = "${profiles::nagios::config_path}/objects/consul_sd_configs/${name}.cfg"
  $consul_template_conf_type = "/etc/consul-template/config-${name}.hcl"

  File {
    owner  => $owner,
    group  => $group,
    mode   => '0644',
  }
  # $template is the Definition Template for Nagios Host/Service
  file { $template:
    ensure => file,
    source => "puppet:///modules/profiles/nagios/consul-template/${name}.cfg.ctmpl",
    notify => Exec['Testing Nagios Config'],
  }

  # $target is the file generated by consul-template based on $template
  file { $target:
    ensure => file,
  }

  # $consul_template_conf_type is the consul-template config file.
  # This file is to tell which template it should watch, which is $template above in this case.
  file { $consul_template_conf_type:
    ensure  => file,
    content => template('profiles/consul-template/template.hcl.erb'),
  }
}
